---


num_rounds: 3
num_clients: 5
batch_size: 32
num_classes: 10
num_clients_per_round_fit: 5
num_clients_per_round_eval: 5
config_fit: 
  lr: 0.001
  weight_decat: 1e-4
  momentum: 0.9
  local_epochs: 2
